"""OKF index files: one generated `index.md` per vault directory (OKF v0.1, section 6).

An index lists what a directory holds, so a person or an agent can see what is available before
opening any document (progressive disclosure). Per the spec an index has no frontmatter, except
the vault-root index, which declares `okf_version`. Entries are standard Markdown links followed
by the description from the linked document's frontmatter; documents are grouped by `type`.

The indexes are generated and committed (they are what GitHub and Obsidian show when browsing a
folder); `index --check` fails when one is stale, like the table records.
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from okf_showcase.settings import Settings
from okf_showcase.vault import RESERVED, Vault

OKF_VERSION = "0.1"
GENERATED_NOTE = "<!-- Generated by `okf-showcase index`. Do not edit. -->"
TYPE_HEADINGS = {
    "term": "Terms",
    "dataset": "Tables",
    "semantics": "Semantics overlays",
    "data_product": "Data products",
    "concept": "Concepts",
    "bundle": "Bundles",
}


def _directories(root: Path) -> list[Path]:
    dirs = [root] + [p for p in root.rglob("*") if p.is_dir()]
    return sorted(d for d in dirs if not any(part.startswith(".") for part in d.relative_to(root).parts))


def generate(settings: Settings) -> dict[Path, str]:
    vault = Vault(settings.vault)
    root = settings.vault
    descriptions = settings.index_descriptions
    docs_by_dir = defaultdict(list)
    for doc in vault.docs.values():
        docs_by_dir[doc.path.parent].append(doc)

    out = {}
    for directory in _directories(root):
        rel = directory.relative_to(root).as_posix()
        lines = []
        if directory == root:
            lines += ["---", f'okf_version: "{OKF_VERSION}"', "---", ""]
        lines += [GENERATED_NOTE, ""]
        key = "" if rel == "." else rel
        if descriptions.get(key):
            lines += [descriptions[key], ""]

        subdirs = sorted(p for p in directory.iterdir() if p.is_dir() and not p.name.startswith("."))
        if subdirs:
            lines.append("# Directories\n")
            for sub in subdirs:
                key = sub.relative_to(root).as_posix()
                count = sum(1 for p in sub.rglob("*.md") if p.name not in RESERVED)
                text = descriptions.get(key) or f"{count} documents"
                lines.append(f"* [{sub.name}]({sub.name}/index.md) - {text}")
            lines.append("")

        groups = defaultdict(list)
        for doc in docs_by_dir.get(directory, []):
            groups[doc.type].append(doc)
        for type_ in sorted(groups, key=lambda t: TYPE_HEADINGS.get(t, t)):
            lines.append(f"# {TYPE_HEADINGS.get(type_, type_)}\n")
            for doc in sorted(groups[type_], key=lambda d: d.title.lower()):
                summary = doc.meta.get("description") or doc.meta.get("grain") or ""
                lines.append(f"* [{doc.title}]({doc.path.name}) - {summary}".rstrip(" -"))
            lines.append("")
        out[directory / "index.md"] = "\n".join(lines).rstrip() + "\n"
    return out


def write(settings: Settings) -> list[Path]:
    indexes = generate(settings)
    for path, content in indexes.items():
        path.write_text(content, encoding="utf-8")
    return sorted(indexes)


def check(settings: Settings) -> list[str]:
    return [
        f"{path.relative_to(settings.root)}: differs from the generated index"
        for path, content in generate(settings).items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]
