"""Step 1 of the flow: Dataform `.sqlx` files to generated table records in the vault.

One `.sqlx` file becomes one record `knowledge/pipeline/tables/<layer>/<name>.md` with the full
BigQuery address, layer, materialization, partitioning, columns and lineage (`upstream`,
`downstream` as wikilinks). The records are machine-owned: nobody edits them by hand, and
`tables --check` fails when a committed record differs from a fresh generation.

Column descriptions come from two writers (see docs/04-back-to-gcp.md): BigQuery wins for the
projects listed in `bigquery_description_projects`, the Dataform `columns {}` block fills the rest.
`description_source` on each column records which one was used.

Simplification: this reads the `config {}` block straight from the `.sqlx` text. A production
pipeline runs `dataform compile --json` instead, which also resolves JavaScript includes, template
literals and the default project, and reads the column list from BigQuery.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from okf_showcase.settings import Settings
from okf_showcase.vault import RESERVED, render

REF = re.compile(r"""\$\{\s*ref\(\s*["']([^"']+)["'](?:\s*,\s*["']([^"']+)["'])?\s*\)\s*\}""")
GENERATED_NOTE = (
    "<!-- Generated by `okf-showcase tables` from the Dataform repository. Do not edit: change the "
    ".sqlx file, or write curated meaning into knowledge/pipeline/semantics/. -->"
)


@dataclass
class Model:
    name: str
    path: Path
    layer: str
    config: dict[str, Any]
    project: str
    dataset: str
    upstream: list[str]
    downstream: list[str] = field(default_factory=list)

    @property
    def address(self) -> str:
        return f"{self.project}.{self.dataset}.{self.name}"


def extract_config(text: str) -> str:
    """The `{ ... }` object after `config`, found by brace matching outside strings."""
    start = text.find("config")
    if start == -1:
        raise ValueError("no config block")
    open_at = text.index("{", start)
    depth, quote = 0, ""
    for i in range(open_at, len(text)):
        ch = text[i]
        if quote:
            if ch == "\\":
                continue
            if ch == quote and text[i - 1] != "\\":
                quote = ""
        elif ch in "\"'`":
            quote = ch
        elif ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return text[open_at : i + 1]
    raise ValueError("config block is not closed")


def js_object_to_python(source: str) -> dict[str, Any]:
    """Parse a JavaScript object literal of plain values (strings, numbers, lists, objects).

    A small scanner turns it into JSON: unquoted keys get quoted, single-quoted strings become
    double-quoted, `//` comments and trailing commas are dropped, all only outside strings.
    """
    out: list[str] = []
    i, quote = 0, ""
    while i < len(source):
        ch = source[i]
        if quote:
            if ch == "\\" and i + 1 < len(source):
                out.append(source[i : i + 2])
                i += 2
                continue
            if ch == quote:
                out.append('"')
                quote = ""
            else:
                out.append('\\"' if ch == '"' else ch)
        elif ch in "\"'":
            quote = ch
            out.append('"')
        elif source.startswith("//", i):
            while i < len(source) and source[i] != "\n":
                i += 1
            continue
        elif ch.isalpha() or ch == "_":
            j = i
            while j < len(source) and (source[j].isalnum() or source[j] == "_"):
                j += 1
            word, k = source[i:j], j
            while k < len(source) and source[k] in " \t":
                k += 1
            out.append(f'"{word}"' if k < len(source) and source[k] == ":" else word)
            i = j
            continue
        elif ch in "}]":
            while out and out[-1].isspace():
                out.pop()
            if out and out[-1] == ",":
                out.pop()
            out.append(ch)
        else:
            out.append(ch)
        i += 1
    parsed = json.loads("".join(out))
    if not isinstance(parsed, dict):
        raise ValueError("config is not an object")
    return parsed


def load_models(settings: Settings) -> list[Model]:
    workflow = yaml.safe_load((settings.dataform / "workflow_settings.yaml").read_text(encoding="utf-8"))
    definitions = settings.dataform / "definitions"
    models: dict[str, Model] = {}
    for path in sorted(definitions.rglob("*.sqlx")):
        text = path.read_text(encoding="utf-8")
        config = js_object_to_python(extract_config(text))
        name = config.get("name", path.stem)
        models[name] = Model(
            name=name,
            path=path,
            layer=path.relative_to(definitions).parts[0],
            config=config,
            project=config.get("database", workflow["defaultProject"]),
            dataset=config.get("schema", workflow["defaultDataset"]),
            upstream=sorted({m.group(2) or m.group(1) for m in REF.finditer(text)}),
        )
    for model in models.values():
        for parent in model.upstream:
            if parent not in models:
                raise ValueError(f"{model.path}: ref('{parent}') points to no .sqlx file")
            models[parent].downstream.append(model.name)
    return list(models.values())


def load_bigquery_descriptions(settings: Settings) -> dict[str, dict[str, str]]:
    """Column descriptions per table address, only for the projects BigQuery is read for."""
    snapshot = json.loads(settings.bigquery_snapshot.read_text(encoding="utf-8"))
    return {
        address: columns
        for address, columns in snapshot.items()
        if not address.startswith("_") and address.split(".")[0] in settings.bigquery_description_projects
    }


def record(model: Model, bigquery: dict[str, dict[str, str]], dataform_root: Path) -> str:
    config = model.config
    bq_columns = bigquery.get(model.address, {})
    columns = {}
    for column, dataform_text in (config.get("columns") or {}).items():
        if bq_columns.get(column):
            columns[column] = {"description": bq_columns[column], "description_source": "bigquery"}
        else:
            columns[column] = {"description": dataform_text, "description_source": "dataform"}
    bq = config.get("bigquery") or {}
    meta: dict[str, Any] = {
        "title": model.name,
        "type": "dataset",
        "description": config.get("description", ""),
        "resource": f"bigquery:{model.address}",
        "gcp_project": model.project,
        "layer": model.layer,
        "materialization": config.get("type", "table"),
        "dataform_path": model.path.relative_to(dataform_root).as_posix(),
        "tags": list(config.get("tags", [])),
        "partition_by": bq.get("partitionBy"),
        "cluster_by": bq.get("clusterBy"),
        "upstream": [f"[[{name}]]" for name in model.upstream],
        "downstream": [f"[[{name}]]" for name in sorted(model.downstream)],
        "columns": columns,
    }
    meta = {key: value for key, value in meta.items() if value not in (None, [], "")}
    rows = "\n".join(
        f"| `{name}` | {col['description']} | {col['description_source']} |" for name, col in columns.items()
    )
    body = (
        f"{GENERATED_NOTE}\n\n# `{model.name}`\n\n{meta['description']}\n\n"
        f"**BigQuery:** `{model.address}`\n\n"
        f"## Columns\n\n| Column | Description | Source |\n| :-- | :-- | :-- |\n{rows}\n"
    )
    return render(meta, body)


def generate(settings: Settings) -> dict[Path, str]:
    """Every table record as {path: content}, without writing anything."""
    bigquery = load_bigquery_descriptions(settings)
    out = {}
    for model in load_models(settings):
        target = settings.vault / "pipeline" / "tables" / model.layer / f"{model.name}.md"
        out[target] = record(model, bigquery, settings.dataform)
    return out


def _existing(tables_dir: Path) -> set[Path]:
    return {p for p in tables_dir.rglob("*.md") if p.name not in RESERVED}


def write(settings: Settings) -> list[Path]:
    tables_dir = settings.vault / "pipeline" / "tables"
    records = generate(settings)
    for stale in _existing(tables_dir) - set(records):
        stale.unlink()
    for path, content in records.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return sorted(records)


def check(settings: Settings) -> list[str]:
    """Differences between the committed records and a fresh generation (the generated-file guard)."""
    tables_dir = settings.vault / "pipeline" / "tables"
    records = generate(settings)
    problems = [
        f"{path.relative_to(settings.root)}: differs from the generated record"
        for path, content in records.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]
    problems += [
        f"{path.relative_to(settings.root)}: no .sqlx file generates this record"
        for path in sorted(_existing(tables_dir) - set(records))
    ]
    return problems
